<!DOCTYPE html>
<html>
<head>
    <title>Elfet's Chat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="<?=$basePath?>/css/chat.css">
</head>
<body>
<div class="container">
    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>
    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>
    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>
    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>
    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>
    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>
    <div class="message">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>

    <div class="message my">
        <a class="user" href=""><img src="<?=$user['pic_square']?>" title="<?=$user['name']?>"></a>
        <div class="text">Hello World!</div>
    </div>
</div>
<div class="control">
    <input type="text" name="message" id="message" placeholder="Type message and press Enter">
</div>
</body>
</html>