<!DOCTYPE html>
<html>
<head>
    <title>Elfet's Chat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="<?=$basePath?>/css/login.css">
</head>
<body>
<div class="container">
    <a style="margin: 0 auto; display: block; width: 50px;" href="<?=$this['url_generator']->generate('logout')?>">
        <img src="<?=$user['pic_square']?>" title="<?=$user['name']?>" style="border-radius: 50%;">
    </a>
</div>
</body>
</html>